# This workflow will install Python dependencies, run tests with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Unit tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          # Python 3.7 binaries are only published for Ubuntu 22.04/20.04, not 24.04
          - os: ubuntu-22.04
            python-version: "3.7.17"
          - os: ubuntu-latest
            python-version: "3.8"
          - os: ubuntu-latest
            python-version: "3.9"
          - os: ubuntu-latest
            python-version: "3.10"
          - os: ubuntu-latest
            python-version: "3.11"
          - os: ubuntu-latest
            python-version: "3.12"

    steps:
    - uses: actions/checkout@v4
    - name: Install Go for p2pd
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'
    - name: Install nodejs for jsp2pd
      uses: actions/setup-node@v4
      with:
        node-version: '16'
    - uses: actions/cache@v4
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - name: Install p2pd
      run: bash -x scripts/install_p2pd.sh
    - name: Install jsp2pd
      run: npm install --global libp2p-daemon@0.10.2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Python dependencies
      run: |
        pip install -e .[test]
    - name: Check types
      run: |
        if python -c "import sys; exit(0 if sys.version_info >= (3, 9) else 1)"; then
          mypy p2pclient
        else
          echo "Skipping mypy check for Python ${{ matrix.python-version }} (requires Python 3.9+)"
        fi
    - name: Run unit tests with p2pd
      run: |
        pytest -v --daemon=p2pd .
    - name: Run unit tests with jsp2pd
      run: |
        pytest -v --daemon=jsp2pd .
